development:
  adapter: postgresql
  encoding: unicode
  database: flixter1_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: flixter1_test
  pool: 5
  username: postgres
  password: password
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: flixter1_production
  pool: 5
  username: postgres
  password: password
  host: localhost
